version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
      - image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
        environment:
          discovery.type: single-node
          xpack.security.enabled: "false"
          xpack.security.http.ssl.enabled: "false"
    steps:
      - checkout

      

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install elasticsearch==8.10.0


      - run:
          name: Run your Python script
          command: python python.py

workflows:
  build_now:
    jobs:
      - build
