version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install elasticsearch
      
      - run: python python.py   

workflows:
  build_now:
    jobs:
      - build